version: '3.8'

services:

  myapp:
    container_name: ServiceGuideBack
    build: .
    image: myapp:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=-Xmx384m
    command: java -jar /app/target/serviceguideBackend.jar
    networks:
      - serviceguide-postgres_default

networks:
  serviceguide-postgres_default:
    external: true