version: '3.8'

services:
  myapp:
    container_name: ServiceGuideBack
    build: .
    ports:
      - "5001:5001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    image: myapp:latest
    command: java -jar /app/target/serviceguideBackend.jar