version: '3.8'

services:
  myapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    image: myapp:latest
    command: java -jar /app/target/serviceguideBackend.jar